### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/ICSurvivalServerPlugin#5]
[05:15:39 INFO]: UUID of player Cosmixing is 7b37f1f9-2e08-4d98-84bb-9a252f0f1a17
[05:15:39 WARN]: [IntrovertsCoveSurvivalServer] Task #156473 for IntrovertsCoveSurvivalServer v1.0-INDEV generated an exception
java.lang.NullPointerException: null
        at net.introvertscove.survivalserver.plugin.listeners.PlayerLoginLogoutListener$1.run(PlayerLoginLogoutListener.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-444]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-444]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[05:15:39 INFO]: <MasonLF> k
[05:15:40 INFO]: [IntrovertsCove] The member data for 7b37f1f9-2e08-4d98-84bb-9a252f0f1a17 couldn't be found. WHAT IS HAPPENING!!!
[05:15:40 INFO]: Cosmixing joined the game

**Comment by JustBru00** [comment]
Caused by attempting to set player to spectator gamemode in the player preloginevent, the player can take more than 5 ticks to login and this causes Bukkit.getPlayer() to return null.  This logic should be moved to the PlayerJoin Event.
